/* eslint-disable prettier/prettier */
export type ProjectImage = {
  src: string;
  alt: string;
};

function createImages(
  folder: string,
  projectName: string,
  filenames: string[],
): ProjectImage[] {
  return filenames.map((filename) => ({
    src: `${folder}/${filename}`,
    alt: `${projectName} project`,
  }));
}

export const projectImages: Record<string, ProjectImage[]> = {
  "biodigester1": createImages(
    "/images/projects/biodigester/biodigester1",
    "Biodigester",
    [
      "image1.jpeg",
      "image2.jpeg",
      "image3.jpeg",
      "image4.jpeg",
      "image5.jpeg",
      "image6.jpeg",
      "image7.jpeg",
    ],
  ),

  "building-project-1": createImages(
  "/images/projects/building/building-project-1",
  "Building Project 1",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
    "img16.jpeg",
    "img17.jpeg",
  ],
),
"building-project-2": createImages(
  "/images/projects/building/building-project-2",
  "Building Project 2",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
    "img16.jpeg",
    "img17.jpeg",
    "img18.jpeg",
    "img19.jpeg",
    "img20.jpeg",
  ],
),
"building-project-3": createImages(
  "/images/projects/building/building-project-3",
  "Building Project 3",
  [
    "img1.jpeg",
    "img2.jpeg",
  ],
),
"building-project-4": createImages(
  "/images/projects/building/building-project-4",
  "Building Project 4",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
  ]
),
"building-project-5": createImages(
  "/images/projects/building/building-project-5",
    "Building Project 5",
 [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
  ]
),
 "carshades-and-automation": createImages(
  "/images/projects/car-shades-gates/carshades-and-automation",
  "Car Shades & Automation",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
    "img16.jpeg",
    "img17.jpeg",
    "img18.jpeg",
    "img19.jpeg",
    "img20.jpeg",
    "img21.jpeg",
    "img22.jpeg",
    "img23.jpeg",
    "img24.jpeg",
    "img25.jpeg",
    "img26.jpeg",
    "img27.jpeg",
    "img28.jpeg",
    "img29.jpeg",
    "img30.jpeg",
    "img31.jpeg",
    "img32.jpeg",
    "img33.jpeg",
    "img34.jpeg",
    "img35.jpeg",
    "img36.jpeg",
    "img37.jpeg",
    "img38.jpeg",
    "img39.jpeg",
    "img40.jpeg",
    "img41.jpeg",
    "img42.jpeg",
    "img43.jpeg",
    "img44.jpeg",
    "img45.jpeg",
    "img46.jpeg",
    "img47.jpeg",
    "img48.jpeg",
    "img49.jpeg",
    "img50.jpeg",
    "img51.jpeg",
    "img52.jpeg",
    "img53.jpeg",
    "img54.jpeg",
    "img55.jpeg",
    "img56.jpeg",
    "img57.jpeg",
    "img58.jpeg",
  ],
),
"fences1": createImages(
  "/images/projects/fences/fences1",
  "Fencing",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
  ],
),
"home-renovation1": createImages(
  "/images/projects/home-renovations/home-renovation1",
  "Home Renovation Project 1",
  [
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
  ],
),
"home-renovation2": createImages(
  "/images/projects/home-renovations/home-renovation2",
  "Home Renovation Project 2",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
    "img16.jpeg",
    "img17.jpeg",
    "img18.jpeg",
    "img19.jpeg",
    "img20.jpeg",
    "img21.jpeg",
    "img22.jpeg",
    "img23.jpeg",
    "img24.jpeg",
    "img25.jpeg",
    "img26.jpeg",
    "img27.jpeg",
    "img28.jpeg",
    "img29.jpeg",
    "img30.jpeg",
    "img31.jpeg",
    "img32.jpeg",
    "img33.jpeg",
    "img34.jpeg",
    "img35.jpeg",
    "img36.jpeg",
    "img37.jpeg",
    "img38.jpeg",
    "img39.jpeg",
  ],
),
"home-renovation3": createImages(
  "/images/projects/home-renovations/home-renovation3",
  "Home Renovation Project 3",
  [
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
    "img16.jpeg",
    "img17.jpeg",
    "img18.jpeg",
    "img19.jpeg",
    "img20.jpeg",
    "img21.jpeg",
    "img22.jpeg",
    "img23.jpeg",
    "img24.jpeg",
    "img25.jpeg", 
    "img26.jpeg",
    "img27.jpeg",  
  ],
),
"home-renovation4": createImages(
  "/images/projects/home-renovations/home-renovation4",
  "Home Renovation Project 4",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
    "img16.jpeg",
  ]
),
"home-renovation5": createImages(
  "/images/projects/home-renovations/home-renovation5",
  "Home Renovation Project 5",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
    "img16.jpeg",
  ]
),
"infrastructure1": createImages(
  "/images/projects/infrastructure/infrastructure1",
  "Infrastructure Project 1",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
    "img13.jpeg",
    "img14.jpeg",
    "img15.jpeg",
    "img16.jpeg",
    "img17.jpeg",
    "img18.jpeg",
    "img19.jpeg",
    "img20.jpeg",
  ]
),
"infrastructure2": createImages(
  "/images/projects/infrastructure/infrastructure2",
  "Infrastructure Project 2",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
    "img7.jpeg",
    "img8.jpeg",
    "img9.jpeg",
    "img10.jpeg",
    "img11.jpeg",
    "img12.jpeg",
  ]
),
"infrastructure3": createImages(
  "/images/projects/infrastructure/infrastructure3",
  "Infrastructure Project 3",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
    "img4.jpeg",
    "img5.jpeg",
    "img6.jpeg",
  ]
),
"property-management1": createImages(
  "/images/projects/property-management/property-management1",
  "Property Management Project 1",
  [
    "img1.jpeg",
    "img2.jpeg",
    "img3.jpeg",
  ]
),
}

export function getProjectImages(slug: string): ProjectImage[] {
  return projectImages[slug] ?? [];
}